spring.application.name=authify
spring.datasource.url=jdbc:mysql://localhost:3306/authify_app
spring.datasource.username=root
spring.datasource.password=Kishan@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret.key = thisisthesecretkeyforauthdevelopmentkishanmauryafgergergeg

server.servlet.context-path=/api

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=993ae0001@smtp-brevo.com
spring.mail.password=jYPx80cFZkL2A7Ea
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=kkmaurya.0095@gmail.com
